name: e2e-tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Run tests from the Makefile
          env:
            JUNIT_DIRECTORY: /artifacts
          shell: bash
          run: |
            make -f x.mk hello

