name: e2e-tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Run tests from the Makefile
          run: |
            echo "Hello World"
            echo ${{ github.workspace }}
            tree
            make -f x.mk e2e-local
        - name: Archive production artifacts
          uses: actions/upload-artifact@v1
          with:
            name: output
            path: ${{ github.workspace }}/test/e2e/junit_e2e.xml