name: e2e-tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Run tests from the Makefile
          shell: bash
          run: |
            value=`find . -name *.xml`
            echo The result is $value

